### ISSUE TITLE
Old REST API deprecated

### ISSUE THREAD

**Issue by DubhAd** [abdullahselek/HerePy#18]
It's no longer possible to create an APP CODE, it's now either OAUTH2 or API keys. This means that anybody trying to use this for the first time now can't.

Somebody reported this today in the HA Discord, and I've verified it myself.

**Comment by eifinger** [comment]
Can you please link the herepy issue to this issue?

**Comment by DubhAd** [comment]
https://github.com/home-assistant/home-assistant/issues/29921

**Comment by abdullahselek** [comment]
Hi @DubhAd @eifinger I just opened a PR #19 please have a look.

**Comment by eifinger** [comment]
@abdullahselek this can now be closed.
