### ISSUE TITLE
Getting Error while running the API

### ISSUE THREAD

**Issue by gmehta1996** [abdullahselek/HerePy#32]
Following is the error:
This is the same for 'address_with_detail' , 'address_with_boundingbox' etc.

Traceback (most recent call last):
  File "C:\Users\Desktop\Python_Folder\test.py", line 143, in <module>
    response = geocoderApi.free_form('200 S Mathilda Sunnyvale CA')
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\herepy\geocoder_api.py", line 58, in free_form
    return self.__get(data)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\herepy\geocoder_api.py", line 40, in __get
    raise HEREError(json_data.get('Details', 'Error occured on function ' + sys._getframe(1).f_code.co_name))
herepy.error.HEREError: Error occured on function free_form

**Comment by abdullahselek** [comment]
Hi @gmehta1996 are you sure that you use the correct API key?

**Comment by gmehta1996** [comment]
Yes I thik so..I created an app and generated the api key and used it.

**Comment by gmehta1996** [comment]
Hi , the API issue was resolved but I would like to know that can we use the Routing API to get the route between two points and display the route on an openstreetmap?? If yes then how?

**Comment by abdullahselek** [comment]
It is possible, you can use one of the methods in `RoutingApi` to calculate the route. Showing the calculated route on OpenStreetMap depends on you not to this Python module.
