### ISSUE TITLE
Correct usage of places_in_circle

### ISSUE THREAD

**Issue by mikhailsirenko** [abdullahselek/HerePy#34]
Hi Abdullah,

Thanks a lot for a robust and nicely document package! I tried to request a set of places within a city with a given radius with `place_in_circle`, but it seems that there is a limit on the radius of the circle? Or maybe there is a limit on the number of places that I can retrieve? For example, the following query with a radius of 10000 m results only in 20 places.

![image](https://user-images.githubusercontent.com/40139771/104895426-2a8f9d00-5976-11eb-96ad-29baef526e5a.png)

**Comment by abdullahselek** [comment]
Hi @mikhailsirenko,

Thanks for your interest at HerePy. You are right there was a limit parameter on endpoint and is missing on `places_in_circle` method. I am gonna add this support and let you know.

**Comment by abdullahselek** [comment]
I've just released a patch v3.2.1 that I think it solves your problem. Usage as below

**Comment by mikhailsirenko** [comment]
@abdullahselek thanks! Just tested the patch, it works as expected!
