### ISSUE TITLE
Adding maptiles and vectortiles?

### ISSUE THREAD

**Issue by deeplook** [abdullahselek/HerePy#35]
I've stumbled of this project again, which looks very interesting! I'm just missing maptiles and vectortiles. Any plans to support these?

**Comment by abdullahselek** [comment]
Hi @deeplook, thanks for your interest and message. Definitely I have plans to support both map and vector tiles APIs.

**Comment by forkbabu** [comment]
@abdullahselek 3.2.1 doesn't support MapTileApi yet right?

**Comment by abdullahselek** [comment]
It is under development right now @forkbabu will be available on new release.

**Comment by abdullahselek** [comment]
With new release v3.3.0 Map and Vector tiles APIs are available.

**Comment by abdullahselek** [comment]
Hi @deeplook and @forkbabu, have you guys had a chance to check the last version? I would like to close this issue as it is available on last release.

**Comment by abdullahselek** [comment]
Closing issue.
