### ISSUE TITLE
RouteMode in Matrix request

### ISSUE THREAD

**Issue by tomatoes-prog** [abdullahselek/HerePy#36]
Hello,

I am new using the Here Mobility API and i am trying to reply the routing_api.Matrix example of the docs. The example says:

```
from herepy import RoutingApi, RouteMode
routing_api = RoutingApi(api_key="api_key")
response = routing_api.matrix(
    start_waypoints=[[9.933231, -84.076831]],
    destination_waypoints=[[9.934574, -84.065544]],
)
print(response.as_dict())
```

But when i use my own api_key i got this error

```
Traceback (most recent call last):
  File "<input>", line 7, in <module>
  File "D:\Repositorios\operaciones-r-rounting\pyport\App\Python\lib\site-packages\herepy\routing_api.py", line 382, in matrix
    response = self.__get(self.URL_CALCULATE_MATRIX, data, RoutingMatrixResponse)
  File "D:\Repositorios\operaciones-r-rounting\pyport\App\Python\lib\site-packages\herepy\routing_api.py", line 43, in __get
    raise error_from_routing_service_error(json_data)
herepy.routing_api.InvalidInputDataError: Transport type 'unknown' is not supported.
```

I think the problem is in the **modes** or **summary_attributes** of the function, and the documentation says 

>  modes (List):
>             List of RouteMode enums following [Type, TransportMode, TrafficMode, Feature].
>  summary_attributes (List):
>             List of MatrixSummaryAttribute enums.

            
So I guess i should put some kind of RouteMode elements in a List but i dont know what does type, transport mode, traffic mode and feature mean. I have tried [RouteMode.fastest, RouteMode.car, RouteMode.traffic_default, RouteMode.traffic_default] but i get the following error:

  ```
File "D:\Repositorios\operaciones-r-rounting\pyport\App\Python\lib\site-packages\herepy\routing_api.py", line 43, in __get
    raise error_from_routing_service_error(json_data)
herepy.routing_api.InvalidInputDataError: Invalid input parameter value
```

Can somebody suggest me how should I put the params if I want to get the od_matrix with flexible mode and a carFast profile?

**Comment by abdullahselek** [comment]
Hi @tomatoes-prog thanks for opening the issue. As I have seen from your message you had used the same route mode twice that might be the reason you got an error.

Please try the code snippet below

**Comment by tomatoes-prog** [comment]
Thank you, I really appreciate your help!
