### ISSUE TITLE
Multiple Waypoints on route_v8

### ISSUE THREAD

**Issue by PechioA** [abdullahselek/HerePy#44]
Hello,

Thanks for making this library available, it is great.

I was wondering, is there a way to use route_v8 using multiple waypoints? ( via )
I checked the source code and it does not seems possible right now.

`via: Optional[List[float]] = None,`

`data["via"] = str.format("{0},{1}", via[0], via[1])`

Yet is seems possible by their rest api:

`'https://router.hereapi.com/v8/routes?origin=52.51375,13.42462&transportMode=car&destination=52.52332,13.42800&via=52.517871,13.434175&via=52.52426,13.43000&return=polyline,summary&apiKey={YOUR_API_KEY}'`

I will use the REST API for this, but it would be awesome to have this feature into the library sometime in the future.

**Comment by abdullahselek** [comment]
Thanks for letting me know, it is fixed available in master branch. Changes will be reflected on next release.
