### ISSUE TITLE
Include all params for the Matrix Routing API

### ISSUE THREAD

**Issue by clequesne** [abdullahselek/HerePy#45]
Hi Abdullah

I am trying to solve an issue with avoiding certain areas or route features when planning routes for my company. The avoid parameter for the matrix routing would be very helpful here but I cannot use this parameter in the API module you have built.

Please could you look at updating the module to include this and any other missing parameters in the matrix routing?

**Comment by abdullahselek** [comment]
Hi @clequesne I added all available parameters to matrix routing api. Install from latest master and give it go also let me know the result.

**Comment by clequesne** [comment]
Thanks very much! This will definitely be helpful! I'll have a go this week and let you know if I have any more issues :)

**Comment by clequesne** [comment]
Working great! Can now specify a tunnel in the Thames to avoid from the distance calculations! :)
