### ISSUE TITLE
sync_matrix required fields

### ISSUE THREAD

**Issue by clequesne** [abdullahselek/HerePy#46]
Hi Abdullah

I am trying to use the sync_matrix function to test that the avoid parameter is working for me, however I came across another issue.

It seems like 'center' and 'radius' are required parameters of the function, however this should only be the case when the specified matrix_type is "circle". I should be able to specify "world" and not have to input these parameters. Is this something you can fix? In the meantime I will try and use the circle type.

![image](https://user-images.githubusercontent.com/83086133/116990027-7585b400-acca-11eb-8bfc-76386be3c9e8.png)

**Comment by abdullahselek** [comment]
Hi @clequesne try installing from latest and give it go. Also I would suggest you to read the documentation I can see some wrong usage of parameters on sync_matrix.

**Comment by clequesne** [comment]
Hi Abdullah - yes I figured out the correct syntax for the parameters although I don't think it makes a difference to the issue at hand.

As I said, the 'world' parameter here should mean I don't need radius and center defined according to the HereAPI documentation, but it does require this in HerePy. Not a major issue because it doesn't seem to be using the circle and radius input I use anyway if I use 'World' but I don't think they should be required fields in sync_matrix unless you're using MatrixRoutingType.Circle

Let me know if you still think my parameter usage is wrong:

![image](https://user-images.githubusercontent.com/83086133/117283393-a6e2b900-ae5d-11eb-9bdd-5dd93845df8e.png)

**Comment by abdullahselek** [comment]
Hi @clequesne providing parameters to routing api is the responsibility of users, I don't think limiting the parameters is a good idea. Have you tried installing the latest from master? You can also use `MatrixSummaryAttribute` enums in a list for `matrix_attributes` parameter.

**Comment by abdullahselek** [comment]
Closing this ticket because of inactivity.
