### ISSUE TITLE
Typo error on "public_transit_api.py"

### ISSUE THREAD

**Issue by frapizzato** [abdullahselek/HerePy#5]
Hi! Just started using your repo and found an error while trying to use the method *calculate_route* for the PublicTransitApi. Scanning through the code I found that the error was while creating data variable and changed line 231 of *public_transit_api.py* from:  
```'arr': str.format('{0}.{1}', arrival[0], arrival[1])```, to:
 ```'arr': str.format('{0},{1}', arrival[0], arrival[1])``` (just changed dot to comma)

Hope this will be useful :)

**Comment by abdullahselek** [comment]
Hi @frapizzato thanks for the information you have provided, I have just updated 👍
