### ISSUE TITLE
Use HerePy behind a proxy

### ISSUE THREAD

**Issue by dschmag** [abdullahselek/HerePy#52]
I could not find any information to pass the proxy information to herepy 
In the code the requests are not using any proxy information
`        response = requests.get(url, timeout=self._timeout)
`
I guess to add the proxy 
`response = requests.get(url, timeout=self._timeout, proxies=self._proxy)`
would be needed.
Or are there other options?

**Comment by dschmag** [comment]
Remark: This issue was on windows. 
I figured out that it's possible to set environment variables HTTP_PROXY which are used for the application

**Comment by abdullahselek** [comment]
Hi @dschmag thanks for reaching out, herepy is a APIClient for now I don't have any plans to support proxies. Let me know if you solved your issue.

**Comment by dschmag** [comment]
Thx, @abdullahselek
I guess the variant to set the env variable should be sufficient and if anyone has the same problem it is documented within this issue.
