### ISSUE TITLE
`'via_keys' referenced before assignment` not resolved even after committing.

### ISSUE THREAD

**Issue by D3nii** [abdullahselek/HerePy#53]
Hi,

I noticed and resolved this issue in my commit `8d08a4435ffa339eec176e5da955483d1409c748` but upon installing `herepy` from `pip`, the error persists.

When can we expect the changes to be reflected in pip?

Regards,
Muhammad Danyal Jamil.

**Comment by abdullahselek** [comment]
Hi @D3nii, latest version `3.5.3` should have your fixes. Please check and let me know.

**Comment by D3nii** [comment]
Hi @abdullahselek, My `requirements.txt` was not updated, thanks!
