### ISSUE TITLE
Route summary not showing properly

### ISSUE THREAD

**Issue by fortiseven** [abdullahselek/HerePy#61]
Hello,

I've recently started using the HERE API for my own curiosity, and I'm using this library for my tests. Though there's something I don't understand. 

I am trying to get the time result of a route calculation considering a specific time given. I noticed it doesn't work on the v7 of RoutingApi, so I tested the v8 on a REST Client, I saw it worked, so I decided to use the route_v8 function to get the same result. Though the JSON given by the function doesn't match the one I get in the REST Client: the summary part appears on my REST Client with the time and distance, but on python I get something else, I get a "polyline" section with tons of numbers and letters.

Is it a bug, or is there something I didn't do right ? I looked at the documentation, but didn't see anything about it. Maybe I missed something.

**Comment by abdullahselek** [comment]
Hello,

Thanks for your interest on herepy. Default value of `return_fields` parameter set as `[RoutingApiReturnField.polyline]` and it accepts a list of RoutingApiReturnField enums try providing a different value.

**Comment by fortiseven** [comment]
Ah ok, I've set the return_fields to [RoutingApiReturnField.summary], works as intended now, thanks for the info.

**Comment by abdullahselek** [comment]
Good to hear that you managed to get a better response. I'm closing the issue if you have any other questions feel free to open a new issue.
