### ISSUE TITLE
Is it possible to make a batch request with HerePy?

### ISSUE THREAD

**Issue by lcoandrade** [abdullahselek/HerePy#62]
I'm trying to geocode more than 4000 addresses and I would like to use you library. Is it possible?

**Comment by abdullahselek** [comment]
Technically it is possible you can use herepy, but you also need to check your HERE developer account to learn if your account has the enough quota.

**Comment by lcoandrade** [comment]
Could you provide a small example of the use of your library to make a batch request?

**Comment by abdullahselek** [comment]
You can always check https://herepy.abdullahselek.com/ for the documentation and `examples` folder in the repo, I believe both has enough details.

**Comment by Talkless** [comment]
> You can always check https://herepy.abdullahselek.com/ for the documentation and `examples` folder in the repo, I believe both has enough details.

I don't see batch geocoding examples.
