### ISSUE TITLE
GeocoderAutoCompleteApi.limit_results_byaddress doesn't work

### ISSUE THREAD

**Issue by efongue-tf** [abdullahselek/HerePy#65]
Hello,
The function : `limit_results_byaddress` of the module `GeocoderAutoCompleteApi` doesn't work.
This is due to the base_url :
self._base_url = "https://autosuggest.search.hereapi.com/v1/autosuggest"
and it should be : 
self._base_url = "https://autocomplete.search.hereapi.com/v1/autocomplete" 

The autosuggest should only be used for `address_suggestion` not for `limit_results_byaddress`

here is the link :
https://github.com/abdullahselek/HerePy/blob/master/herepy/geocoder_autocomplete_api.py

Best regards,
Etienne Fongue

**Comment by abdullahselek** [comment]
Hi @efongue-tf please feel free to open a PR for your recommended changes, I would be happy to review and merge.
