### ISSUE TITLE
https://herepy.abdullahselek.com/ gives 'can't find the server' errors

### ISSUE THREAD

**Issue by huonw** [abdullahselek/HerePy#68]
Thank you for publishing and maintaining HerePy!

I noticed that the documentation website https://herepy.abdullahselek.com/ doesn't seem to work at the moment: it's linked in the README and the Github metadata, and I see that CI theoretically publishes to it. 

For instance, visiting in Safari shows:

![image](https://user-images.githubusercontent.com/1203825/171787118-befebe08-c78a-4251-98aa-7ea662a06f33.png)

**Comment by abdullahselek** [comment]
Hi @huonw thanks for opening the issue and let me know the problem. I've just try opening the link in different browsers including Safari and it worked for me. Please try again and let me know if you still see the issue.

**Comment by huonw** [comment]
You're right, it seems to be working for me again. Sorry for the noise!
