### ISSUE TITLE
v8 Rollout

### ISSUE THREAD

**Issue by James-Burgess** [abdullahselek/HerePy#79]
I see there is code in the routing api for use with v8 `route_v8` is there a roadmap for other functions to be deprecated and for this to change to `route`?

**Comment by abdullahselek** [comment]
I don't think I have a roadmap for depreciation the v7 if route API. But thanks for asking, I'll check.

**Comment by James-Burgess** [comment]
Awesome, I've just upgraded to `route_v8` as my new account [previous account was deleted due to their new account system] didnt seem to be able to hit the old route.
