### ISSUE TITLE
'GeocoderResponse' object is not subscriptable using HERE API wrapper in python

### ISSUE THREAD

**Issue by deekshantsaxena** [abdullahselek/HerePy#8]

**Comment by abdullahselek** [comment]
Hi @deekshantsaxena thanks your using HerePy, could you please give more details? Like how you use geocoder api?

**Comment by deekshantsaxena** [comment]
hi i used it for geocoder free text Geocoder API response, but i am not able to extract details of lat long from the response, it says it is geocoder response and can move further to convert in json or dict , can you help extract lat lon from response

geocoderApi = herepy.GeocoderApi('app_id', 'app_code')
response = geocoderApi.free_form('200 S Mathilda Sunnyvale CA')

**Comment by abdullahselek** [comment]
You can convert any response model to a dictionary with using `as_dict` function which is available already on models. Like `dict = response.as_dict()` and then you can reach lat lon.

Also be sure that you have a valid app_id and app_code.

**Comment by deekshantsaxena** [comment]
Thanks AbdullahSelek for your response it helped, apologies for delayed acknowledgement, can you help me extract latlong, i am using method { print (dict ['Response']['View'])} but it is not going it lat long, following output i received post doing as.dict()  (how do i get/parse display lat long) :

{'Response': {'MetaInfo': {'Timestamp': '2019-09-13T07:53:57.388+0000'},
  'View': [{'_type': 'SearchResultsViewType',
    'ViewId': 0,
    'Result': [{'Relevance': 1.0,
      'MatchLevel': 'houseNumber',
      'MatchQuality': {'State': 1.0,
       'City': 1.0,
       'Street': [0.9],
       'HouseNumber': 1.0},
      'MatchType': 'pointAddress',
      'Location': {'LocationId': 'NT_nL.dzNwdSJgdcF4U8dYEiC_yADM',
       'LocationType': 'point',
       'DisplayPosition': {'Latitude': 37.37634, 'Longitude': -122.03405},
       'NavigationPosition': [{'Latitude': 37.37641, 'Longitude': -122.03444}],
       'MapView': {'TopLeft': {'Latitude': 37.3774642,
         'Longitude': -122.0354646},
        'BottomRight': {'Latitude': 37.3752158, 'Longitude': -122.0326354}},
       'Address': {'Label': '200 S Mathilda Ave, Sunnyvale, CA 94086, United States',
        'Country': 'USA',
        'State': 'CA',
        'County': 'Santa Clara',
        'City': 'Sunnyvale',
        'District': 'Heritage District',
        'Street': 'S Mathilda Ave',
        'HouseNumber': '200',
        'PostalCode': '94086',
        'AdditionalData': [{'value': 'United States', 'key': 'CountryName'},
         {'value': 'California', 'key': 'StateName'},
         {'value': 'Santa Clara', 'key': 'CountyName'},
         {'value': 'N', 'key': 'PostalCodeType'}]}}}]}]}}

**Comment by deekshantsaxena** [comment]
i am struggling since 2 days on this, can you help it and any documentation i can refer

**Comment by abdullahselek** [comment]
You can try below code snippet that may help you.

```python
dict = response.as_dict()
position = dict['Response']['View']['Result']['Location']['DisplayPosition']
latitude = position['Latitude']
longitude = position['Longitude']
```

**Comment by deekshantsaxena** [comment]
hi Abdullahselek,

thank you, i tried this now and earlier as well, it is giving following error, not sure where is the problem

TypeError: list indices must be integers or slices, not str

**Comment by deekshantsaxena** [comment]
can you suggest some resolution here

**Comment by abdullahselek** [comment]
You are trying to read data with key from list which is not possible, you should get by index from list and with string key from dictionary.

**Comment by abdullahselek** [comment]
@deekshantsaxena if you have solved your problem can you close the issue?

**Comment by deekshantsaxena** [comment]
Thanks @abdullahselek for your support
